### ISSUE TITLE
CSV Import Screen

### ISSUE THREAD

**Issue by TheChorb** [FUNDamentSpace/.github#7]
Not sure if this is in progress but the import screen currently only shows instructions, and nowhere to actually import yet :)

**Comment by 4ban** [comment]
Released an hour ago. In an experimental mode, though.

**Comment by TheChorb** [comment]
Import works :) Very cool feature, really loved the ease of categorising mass transactions under each budget. However it doesn't seem to handle the UK date format of DD/MM/YYYY I think its using the USA format of MM/DD/YYYY because it's importing April transactions across the entire 2024 year.
